name: vogon-collector

services:
  timescale:
    image: timescale/timescaledb-ha:pg16
    container_name: vogon-timescale
    restart: unless-stopped
    volumes:
      - timescale_storage:/home/postgres/pgdata/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 5s
      timeout: 30s
      retries: 5

  emqx:
    image: emqx/emqx-enterprise:6.0.0
    container_name: vogon-emqx
    restart: unless-stopped
    ports:
      - 8001:1883
      - 8002:8883
      - 8003:18083
    environment:
      EMQX_LISTENERS__TCP__DEFAULT__AUTHENTICATION__1__DATABASE: ${DB_NAME}
      EMQX_LISTENERS__TCP__DEFAULT__AUTHENTICATION__1__USERNAME: ${DB_USER}
      EMQX_LISTENERS__TCP__DEFAULT__AUTHENTICATION__1__PASSWORD: ${DB_PASSWORD}
      EMQX_LISTENERS__TCP__DEFAULT__AUTHENTICATION__1__SERVER: ${DB_HOST}:${DB_PORT}

      EMQX_AUTHORIZATION__SOURCES__1__DATABASE: ${DB_NAME}
      EMQX_AUTHORIZATION__SOURCES__1__USERNAME: ${DB_USER}
      EMQX_AUTHORIZATION__SOURCES__1__PASSWORD: ${DB_PASSWORD}
      EMQX_AUTHORIZATION__SOURCES__1__SERVER: ${DB_HOST}:${DB_PORT}
    volumes:
      - ./infra/emqx/acl.conf:/opt/emqx/etc/acl.conf
      - ./infra/emqx/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./infra/certs:/opt/emqx/etc/certs
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    healthcheck:
      test: ['CMD', '/opt/emqx/bin/emqx', 'ctl', 'status']
      interval: 5s
      timeout: 30s
      retries: 5
    depends_on:
      timescale:
        condition: service_healthy

  # grafana:
  #   image: grafana/grafana-oss
  #   volumes:
  #     - grafana_storage:/var/lib/grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     database:
  #       condition: service_healthy

  vogon:
    container_name: vogon-collector
    restart: unless-stopped
    ports:
      - 8000:3000
    build: .
    image: vogon-collector
    environment:
      TZ: ${TZ}

      HOST: ${HOST}
      PORT: ${PORT}

      APP_KEY: ${APP_KEY}

      LOG_LEVEL: ${LOG_LEVEL}
      NODE_ENV: ${NODE_ENV}

      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}

      PATH_CA_CERT: ${PATH_CA_CERT}
      PATH_CA_KEY: ${PATH_CA_KEY}

      CERT_CLIENT_EXPIRY_YEARS: ${CERT_CLIENT_EXPIRY_YEARS}
    volumes:
      - ./infra/certs:/app/build/infra/certs:ro
    depends_on:
      timescale:
        condition: service_healthy
      emqx:
        condition: service_started

volumes:
  emqx_data:
  emqx_log:
  timescale_storage:
  grafana_storage:
