name: vogon-collector

services:
  timescale:
    image: timescale/timescaledb-ha:pg16
    volumes:
      - timescale_storage:/home/postgres/pgdata/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 10s
      start_period: 30s

  emqx:
    image: emqx/emqx-enterprise:6.0.0
    ports:
      - 1883:1883
      - 8883:8883
      - 18083:18083
    environment:
      EMQX_AUTHORIZATION__SOURCES__1__DATABASE: ${DB_NAME}
      EMQX_AUTHORIZATION__SOURCES__1__USERNAME: ${DB_USER}
      EMQX_AUTHORIZATION__SOURCES__1__PASSWORD: ${DB_PASSWORD}
      EMQX_AUTHORIZATION__SOURCES__1__SERVER: ${DB_HOST}:${DB_PORT}
    volumes:
      - ./emqx/acl.conf:/opt/emqx/etc/acl.conf
      - ./emqx/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./emqx/certs:/opt/emqx/etc/certs
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    healthcheck:
      test: ['CMD', '/opt/emqx/bin/emqx', 'ctl', 'status']
      interval: 5s
      timeout: 25s
      retries: 5

  # grafana:
  #   image: grafana/grafana-oss
  #   volumes:
  #     - grafana_storage:/var/lib/grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     database:
  #       condition: service_healthy

  # vogon:
  #   build: .
  #   environment:
  #     VERBOSE: ${VERBOSE}
  #     LOG_LEVEL: ${LOG_LEVEL}
  #     DEBUG: ${DEBUG}

  #     HOST: ${HOST}
  #     PORT: ${PORT}

  #     DB_NAME: ${DB_NAME}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_HOST: ${DB_HOST}
  #     DB_PORT: ${DB_PORT}

  #     MQTT_HOST: ${MQTT_HOST}
  #     MQTT_PORT: ${MQTT_PORT}
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #     mqtt:
  #       condition: service_started

volumes:
  emqx_data:
  emqx_log:
  timescale_storage:
  grafana_storage:
